#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=98
SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

BIN=/data/nps/npc
CONF=/data/nps/npc.conf

start() {
	service_start $BIN -config=$CONF &
}

stop() {
	service_stop $BIN
}